root: true
extends: 
  - airbnb-base
  - airbnb-typescript/base
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  sourceType: module
  ecmaVersion: 13
plugins:
  - '@stylistic'
  - '@typescript-eslint'
rules:
  brace-style:
    - error
    - stroustrup
  react/react-in-jsx-scope:
    off
  array-element-newline:
    - error
    - multiline: true
  object-curly-newline:
    - error
    - multiline: true
  no-multiple-empty-lines:
    - error
    - max: 1
  no-multi-str: off